### ISSUE TITLE
As a Pryv dev, I need to have supported Node & lib versions

### ISSUE THREAD

**Issue by kebetsi** [pryv/service-core#25]
Node must be upgraded to version 6 to have active LTS until 04/2018 and Express to version 4.

**Tasks**

- [x] update node to v6
- [x] update mongodb driver to latest (v2)
- [x] update minor libs to latest
- [x] update Express to latest (v4) or move to separate issue
 
https://podio.com/pryvcom/py/apps/projects/items/90
